### ISSUE TITLE
2412 Release Checklist

### ISSUE THREAD

**Issue by gus33000** [WOA-Project/SurfaceDuo-Guides#68]
Non exhaustive

- [ ] **Enhance Documentation**: Make the guides easier to follow.
   - [SurfaceDuo Guides](https://github.com/WOA-Project/SurfaceDuo-Guides)

- [ ] **Complete Duo 2 Uninstall Section**: Finalize the uninstall instructions.
   - [SurfaceDuo Guides](https://github.com/WOA-Project/SurfaceDuo-Guides)

- [x] **Finalize and Merge SecureBoot PK Documentation**: Complete and integrate the SecureBoot documentation.
   - [SecureBoot Docs](https://github.com/WOA-Project/SurfaceDuo-Guides/tree/secureboot/DeviceSecurity)

- [ ] **Implement Backup and Restore**: Add backup and restore functionality to the WOA Device Manager. The current idea is to capture an FFU file and restore it.
   - [WOA Device Manager](https://github.com/WOA-Project/WOA-Device-Manager)

- [ ] **Add Uninstall/Revert Feature**: Implement uninstall and revert options in the WOA Device Manager. The current idea is to use a dummy FFU file that restores the original GPT. This needs to account for disk size and handle cases where users have reflashed their boot partition to boot into Windows or Android on demand.
   - [WOA Device Manager](https://github.com/WOA-Project/WOA-Device-Manager)
   - [Dual Boot Guide](https://github.com/WOA-Project/SurfaceDuo-Guides/blob/main/Install/DualBoot.md)

- [x] **Enable Img2Ffu to Generate Both V1 and V2 FFUs**: Currently, it is hardcoded to generate V2 FFUs via a hack.
   - [Img2Ffu Commit for V1 support](https://github.com/WOA-Project/img2ffu/commit/923997fea95a3a153d655ebc1386a18adafe1dd7)

- [x] **Fix Img2Ffu Issue**: Ensure Img2Ffu does not depend on device information when building V1 images, as it currently throws an exception.

- [x] **Automate WCOS Image Building**: Streamline the process of building WCOS images by automating tasks such as copying feature manifests for desktop, removing non-WCOS drivers, and adding WCOS drivers.
   - [WCOS CDG Adaptation Kit Directory](https://github.com/WOA-Project/windows_andromeda_platforms/tree/main/adaptationkits/CDG)
   - [Desktop Definitions](https://github.com/WOA-Project/windows_andromeda_platforms/tree/main/definitions/Desktop/ARM64/Internal)

- [x] **Optimize OSPool Layout**: Create a device layout that fits perfectly to avoid manual extraction from VHDX files. The branch provides more details.
   - [WCOS Branch (img2ffu)](https://github.com/WOA-Project/img2ffu/tree/hack/wcos)

- [ ] **Develop EFI DISKIO Driver for OSPools**: Write a driver to avoid dependency on BS_EFIESP for WCOS images. Refer to the example C# library for parsing SPACEDB partitions, an example driver for binding to partitions and the example DiskIO driver.
    - [Example FS Driver](https://github.com/GunioRobot/Ext2Pkg/blob/master/Src/Ext2.c)
    - [DiskIO Driver](https://github.com/tianocore/edk2/blob/222e2854fe6bed443686e3809f155fd7b824fabd/MdeModulePkg/Universal/Disk/DiskIoDxe/DiskIo.c#L1296)
    - [OSPools Parsing Implementation](https://github.com/gus33000/StorageSpace)

- [x] **Create Repository for CBS Components for 10X**: Build CBS components instead of using hardcoded prebuilt CAB files.
    - [Current CBS Packages (Hardcoded)](https://github.com/WOA-Project/windows_andromeda_platforms/tree/main/adaptationkits/CDG/MSPackages/Microsoft/Andromeda855/ARM64/fre)
    - [CBS Package Generator](https://github.com/gus33000/wskcbsgen)

- [ ] **Investigate FactoryOS Boot Issue**: Determine why FactoryOS does not boot.
    - [FactoryOS Adaptation Kit Directory](https://github.com/WOA-Project/windows_andromeda_platforms/tree/main/adaptationkits/FOS)

- [ ] **Improve DriverUpdater Cleanup and Speed**: Enhance the cleanup process and speed of DriverUpdater, as it is currently slow and inefficient.
    - [DriverUpdater](https://github.com/WOA-Project/DriverUpdater)
    
- [ ] Implement HeatCore adapter for fixing calibration issues on OEMEP and OEMZE

**Comment by gus33000** [comment]
Well lets just say we pulled a sunvalley on this one and we are quite late on schedule, lets just throw the schedule out of the window and reevaluate our next steps with a new issue *next week instead* instead of keep dragging the lipstick on a pig around like SV
